#! /bin/bash
servers=(ec2-52-0-73-113.compute-1.amazonaws.com 
ec2-52-16-219-28.eu-west-1.compute.amazonaws.com 
ec2-52-11-8-29.us-west-2.compute.amazonaws.com 
ec2-52-8-12-101.us-west-1.compute.amazonaws.com 
ec2-52-28-48-84.eu-central-1.compute.amazonaws.com 
ec2-52-68-12-77.ap-northeast-1.compute.amazonaws.com 
ec2-52-74-143-5.ap-southeast-1.compute.amazonaws.com 
ec2-52-64-63-125.ap-southeast-2.compute.amazonaws.com 
ec2-54-94-214-108.sa-east-1.compute.amazonaws.com)

ind=1

if test "$#" -ne 10; then
	echo "wrong num of args found"
	exit 1
fi

while test $ind -lt 11;
do
	n=$(( ind + 1 ))	
	case ${!ind} in
		-p)
			port=${!n}
			ind=$((ind+2))
			;;
		-o)
			origin=${!n}
			ind=$((ind+2))
			;;
		-n)
			name=${!n}
			ind=$((ind+2))
			;;
		-u)
			user=${!n}
			ind=$((ind+2))
			;;
		-i)
			key=${!n}
			ind=$((ind+2))
			;;
		?)
			echo "invalid input"
			exit 1
			;;
	esac
done

for s in "${servers[@]}"
do
	echo "starting servers in " $s
	ssh -i $key $user@$s "cd ~/Proj5/; nohup ./httpserver -p $port -o $origin > /dev/null 2>&1 &"
	echo "started http server..."
	ssh -i $key $user@$s "cd ~/Proj5/; nohup ./performanceReader > /dev/null 2>&1 &"
	echo "started performance reader server..."
done

dnsserver=cs5700cdnproject.ccs.neu.edu
ssh -i $key $user@$dnsserver "cd ~/Proj5/; nohup ./dnsserver -p $port -n $name > /dev/null 2>&1 &"
echo "started dns server"
